# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "sotw-prod-terraform-state-management"
    dynamodb_table = "sotw-lock-table"
    encrypt        = true
    key            = "prod/terraform.tfstate"
    region         = "us-east-1"
  }
}
